steps:
       - name: python:3.7
         args: ["cp", "*.py", "/workspace"]
       - name: python:3.7
         args: ["cp", "*.txt", "/workspace"]
       - name: python:3.7
         args: ["pip", "install", "--upgrade", "pip"]
       - name: python:3.7
         entrypoint: pip
         args: ["install", "-r", "/workspace/requirements.txt", "--user"]
       - name: python:3.7
         args: ["python", "./workspace/compile-pipeline.py"]
       - name: 'gcr.io/cloud-builders/gsutil'
         args: ['cp', '/mlopsdeploypipeline-2.json', 'gs://gcp-practice-0123-18jun2023/docker-kfp-test/kfp-json/']
artifacts:
  objects:
    location: "gs://gcp-practice-0123-18jun2023/docker-kfp-test/kfp-json/"
    paths: ['mlops-pipeline-json-2.json']
