steps:
  - name: python:3.7
    entrypoint: python
    args: ["-m", "pip", "install", "--upgrade", "pip"]
    id: 'UPGRADE pip'
  - name: python:3.7
    entrypoint: pip
    args: ["install", "-r", "cloud-build/src/kfp-batch-prediction/components-3/requirements.txt", "--user"]
    id: 'INSTALL DEPENDENCIES'
    waitFor: ['UPGRADE pip']
  - name: python:3.7
    entrypoint: python
    args: ['compile_pipeline.py']
    id: 'COMPILE_PIPELINE'
    waitFor: ['INSTALL DEPENDENCIES']
  - name: python:3.7
    entrypoint: python
    args: ['upload_pipeline_template.py']
    id: 'UPLOAD PIPELINE TEMPLATE'
    waitFor: ['COMPILE_PIPELINE']
