steps:
    - name: python
        id: 'COMPILE_PIPELINE'
        entrypoint: python
        args: ['compile_pipeline.py']
    - name: python
        id: 'UPLOAD PIPELINE TEMPLATE'
        entrypoint: python
        args: ['upload_pipeline_template.py']
        waitFor: ['COMPILE_PIPELINE']
